# Generated by Django 3.1.7 on 2023-06-14 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spark_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
