# Generated by Django 4.1.2 on 2023-06-15 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spark_app', '0003_auto_20230615_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
